# Site settings
title: BEN`s Blog
SEOTitle: BEN的博客 | BEN`s Blog
header-img: img/post-bg-desk.jpg
email: 714591092@qq.com
description: "Every failure is leading towards success."
keyword: "BEN, BEN`s Blog, 张斌的博客, zhangbin, 张斌, 前端, WEB, WEB前端"
url: "http://zb-0819.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://zb-0819.com/zb-0819/zb-0819.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BEN-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     zhangbin
zhihu_username:     ben-54-22-6
github_username:    zb-0819
facebook_username:  none
jianshu_username:   none
#twitter_username:   none




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 63aef640217ace8ef8fc                           #生成的clientID
  clientSecret: 4e249638418b8f2003049929615ccc00f03da6c3    #生成的clientSecret
  repo: zb-0819.github.io    #仓库名称
  owner: zb-0819    #github用户名
  admin: zb-0819
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: ben-zhangbin.cn               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        #title: "WY",
        #href: "http://zhengwuyang.com"
    },{
        #title: "简书·BY",
        #href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        #title: "Apple",
        #href: "https://apple.com"
    },{
        #title: "Apple Developer",
        #href: "https://developer.apple.com/"
    }
]
